export const projects = [
  {
    title: 'My Biography Site',
    description: "I have desiged and coded my portpfolio site using React, Node.js, Express & MongoDB fom start to finish which you are seeing now. Lot of fetures are availabe in site like site count, feedback, tech blog wrighting, docker imaging, kubernetes, AWS pipelines, AWS Route 53",
    image: '/images/biosite.jpg',
    tags: ['Mongo', 'Express', 'React', 'NextJS', 'Node'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
},
{
  title: 'ClaimsBOT - Its a BOT',
  description: "This is a small BOT design to get the user input related to insurance Claims and create the un-verified Claims in Guidewire Claimcenter application using Soap XML and Soap call",
  image: '/images/claimsbot.jpg',
  tags: ['Java', 'Alice', 'AXML', 'Soap', 'SoapUI'],
  source: 'https://google.com',
  visit: 'https://google.com',
  id: 1,
},
  {
    title: 'PDF Utility - In GUI Automation scripts',
    description: "This tool is used to compare the PDF files with expected PDF tempalate and share the results in excel with matching %",
    image: '/images/pdfcompare.jpg',
    tags: ['Java', 'Pdfutil', 'PDFBox Util',''],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'PDF Utility - Bulk - E2E Automated using Jenkins pipeline',
    description: "This tool is designed using Jenkins, java and PDF Box which is used to compare the bulf PDF files with expected PDF tempalate and share the results in excel and pdf report with matching %",
    image: '/images/pdfcompare.jpg',
    tags: ['Java', 'Pdfutil', 'PDFBox Util','Jenkins', 'API'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'ALM All pass',
    description: "Designed this tool to pass all the test cases in TEST LAB in ALM test managmeent tool, later this has been used to upload the test cases, requirement and other artifacts.",
    image: '/images/alm.jpg',
    tags: ['MSExcel', 'VBA', 'XML', 'SoapUI', 'ALM'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 4,
  },
  {
    title: 'JIRA-XRAY-CUCU Integration',
    description: "Customized the existing framework to adopte the BDD Cucumber fetrue with integrate with JIRA, Jenkins and automatically upload the test execution results in JIRA",
    image: '/images/xrayjira.jpg',
    tags: ['Selenium', 'Cucumber', 'BDD', 'Jeknins', 'JIRA runner'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 5,
  },
  {
    title: 'XML Generator',
    description: "Designed this tool using Excel Macro, VBA scripting which can be used to generate the bigger XML Payload with values each tags and arrayed tags and Then push the same xml in SoapUI to WSDL endpoint and request",
    image: '/images/xml.jpg',
    tags: ['MSExcel', 'VBA', 'XML', 'SoapUI'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 6,
  },

{
  title: 'MAFNextBoot - Hackathon',
  description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
  image: '/images/hackathon.jpg',
  tags: ['React', 'ChatEngine', 'Firebase'],
  source: 'https://google.com',
  visit: 'https://google.com',
  id: 7,
},
  {
    title: 'IasC using Terraform & Anisble',
    description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    image: '/images/terraform.jpg',
    tags: ['React', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 8,
  },
  {
    title: 'Docker Hands-On',
    description: "This is a small project designed for QA team in Mphasis company to include the Jenkins features, Ci/CD pipelines in automation",
      image: '/images/docker.jpg',
      tags: ['React', 'WebRTC'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 9,
  },
  {
    title: 'Kubernetes end-to-end',
    description: "This is a small project designed for GeekCloud team in Mphasis company to demo the Kubernetes features, Ci/CD pipelines",
    image: '/images/k8.jpg',
    tags: [,'Kubectl', 'Minikube', 'kubeadmn', 'React'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 10,
  },
  {
    title: 'Automated Pipeline projects using Jenkins',
    description: "This is a small project designed for GeekCloud team in Mphasis company to demo the Kubernetes features, Ci/CD pipelines",
    image: '/images/cicd.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 11,
  }
];

export const TimeLineData = [
  { year: 2010, text: 'Started my journey as QA Engineer', },
  { year: 2011, text: 'Worked as a Junior automation engineer', },
  { year: 2014, text: 'Innvoted few tools as Automation Assosiate', },
  { year: 2015, text: 'Promoted as Senior Automation enginner', },
  { year: 2017, text: 'Started DevOps Journey', },
  { year: 2018, text: 'Become a Senior SDET DevOps Journey', },
  { year: 2021, text: 'Started my own platform', },
  { year: 2023, text: 'Rocking as Senior SDET and DevOps engineer', }
];